# Generated by Django 4.2.5 on 2023-10-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size_name',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
