# Generated by Django 4.2.6 on 2023-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='product_img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='productimage',
        ),
    ]
