# Generated by Django 4.2.5 on 2023-10-11 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_sizevariant_size_name'),
        ('cart1', '0002_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart1.cart')),
                ('color_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.colorvariant')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('size_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sizevariant')),
            ],
        ),
    ]
